language: generic

install:
- wget https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-1.32.0-x86_64-linux.tar.bz2
- tar xvf dhall-1.32.0-x86_64-linux.tar.bz2
- sudo mv ./bin/dhall /usr/local/bin/dhall

script:
- |
  set -euo pipefail

  for f in $(find . -name '*.dhall'); do
    echo "Checking $f"
    dhall type --quiet --file $f
  done

  echo "Checking if all the cache fingerprints are correct"
  ./scripts/freeze-package-dhalls.sh
  git diff --color --exit-code

  # Required for travis
  set +u
